name: Postman Run Tests With Newman
run-name: ${{ github.actor }} is running Postman tests
on: [push]

jobs:
  Run-Postman-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

#      - name: Check out repository code
#        uses: actions/checkout@v3
#
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#
#
#      - uses: actions/checkout@master
#      - uses: matt-ball/newman-action@master
#        with:
#          collection: user_reg_and_get_item.postman_collection.json
#          environment: Local.postman_environment.json
#          delayRequest: 5000
#          envVar: '[{ "key": "url", "value": "http://localhost:3000" }]'
#
#      - run: echo "🍏 This job's status is ${{ job.status }}."